---
# Note: AWS profiles are loaded directly from ~/.aws/credentials
# and ~/.aws/config files on the system

ui:
  refresh_interval: 30
  default_region: "us-east-1"
  max_buckets_display: 100
  display_preferences:
    show_bucket_size: true
    show_object_count: true
    show_last_modified: true
    show_storage_class: true
    show_versioning: true
    show_encryption: true
  color_scheme:
    public: "red"
    private: "green"
    warning: "yellow"
    heading: "blue"
  sort:
    default_field: "name"
    default_direction: "asc"
  enable_metrics: true
  enable_object_browser: true
  enable_policies_viewer: true
  object_browser:
    max_objects: 1000
    page_size: 50
    supported_actions:
      - download
      - upload
      - delete
      - copy
      - move
  transfer:
    concurrent_uploads: 5
    concurrent_downloads: 5
    max_part_size: 10485760  # 10MB
    enable_multipart: true 